type Mentorship {
    id: ID!
    artist: User!
    mentee: User!
    startDate: String
    endDate: String
    topics: [String!]!
    createdAt: String!
    updatedAt: String!
}

extend type User {
    mentorshipsAsArtist: [Mentorship!]!
    mentorshipsAsMentee: [Mentorship!]!
}

extend type Query {
    mentorship(id: ID!): Mentorship
    mentorships: [Mentorship!]!
}
