type Merchandise {
    id: ID!
    name: String!
    description: String
    price: Float!
    imageUrl: String
    artist: ArtistProfile
    createdAt: String!
    updatedAt: String!
    customizedMerches: [CustomizedMerch]
}
